name: Update Activity Automatically

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  update-activity:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask flask-cors GitPython

      # Step 4: Run the backend.py script
      - name: Run activity updater
        run: |
          python backend.py

      # Step 5: Commit and Push changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md activity.json
          git commit -m "chore: auto-update activity table" || echo "No changes to commit"
          git push
