name: Update README with Medium Articles

on:
  schedule:
    - cron: "0 * * * *" # runs hourly
  workflow_dispatch:

jobs:
  update-readme-with-medium:
    runs-on: ubuntu-latest
    steps:
      - uses: bxcodec/github-readme-medium-recent-article@master
        with:
          username: HimanshuP601
