name: Update Waka README Stats
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update README with waka-readme-stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}    # <-- your PAT stored as GH_TOKEN
          SECTION_NAME: "waka"
          COMMIT_MESSAGE: "chore: update waka stats"
          SHOW_UPDATED_DATE: "True"
